# Generated by Django 3.1.2 on 2023-06-20 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_despachocliente_estadodespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachocliente',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.estadodespacho'),
        ),
    ]
