# Generated by Django 3.1.2 on 2023-06-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230620_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='suscrito',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
